# Generated by Django 5.0.2 on 2024-02-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Ваше Имя')),
                ('email', models.EmailField(max_length=125, unique=True, verbose_name='Ваша Электронная почта')),
                ('subject', models.CharField(max_length=310, verbose_name='Ваш вопрос')),
                ('message', models.TextField(max_length=620, verbose_name='Текст')),
            ],
            options={
                'verbose_name': ('Обратная связь',),
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
